"""add graph fields to memory

Revision ID: 11659cef325e
Revises: 
Create Date: 2026-03-29 09:50:08.201281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11659cef325e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('graph_status', sa.String(length=16), server_default='not_added', nullable=False))
    op.add_column('memories', sa.Column('graph_episode_uuid', sa.String(length=36), nullable=True))
    op.add_column('memories', sa.Column('graph_error', sa.Text(), nullable=True))
    op.add_column('memories', sa.Column('graph_added_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memories', 'graph_added_at')
    op.drop_column('memories', 'graph_error')
    op.drop_column('memories', 'graph_episode_uuid')
    op.drop_column('memories', 'graph_status')
    # ### end Alembic commands ###
